package entidades;
// Generated 02-sep-2016 14:54:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AdmAuditoria generated by hbm2java
 */
public class AdmAuditoria  implements java.io.Serializable {


     private Integer id;
     private AdmUsuario admUsuario;
     private String accion;
     private Date fecha;

    public AdmAuditoria() {
    }

    public AdmAuditoria(AdmUsuario admUsuario, String accion, Date fecha) {
       this.admUsuario = admUsuario;
       this.accion = accion;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AdmUsuario getAdmUsuario() {
        return this.admUsuario;
    }
    
    public void setAdmUsuario(AdmUsuario admUsuario) {
        this.admUsuario = admUsuario;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


