package entidades;
// Generated 02-sep-2016 14:54:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmPermiso generated by hbm2java
 */
public class AdmPermiso  implements java.io.Serializable {


     private Integer id;
     private AdmVista admVista;
     private String descripcion;
     private boolean consulta;
     private Set admRols = new HashSet(0);

    public AdmPermiso() {
    }

	
    public AdmPermiso(AdmVista admVista, String descripcion, boolean consulta) {
        this.admVista = admVista;
        this.descripcion = descripcion;
        this.consulta = consulta;
    }
    public AdmPermiso(AdmVista admVista, String descripcion, boolean consulta, Set admRols) {
       this.admVista = admVista;
       this.descripcion = descripcion;
       this.consulta = consulta;
       this.admRols = admRols;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AdmVista getAdmVista() {
        return this.admVista;
    }
    
    public void setAdmVista(AdmVista admVista) {
        this.admVista = admVista;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(boolean consulta) {
        this.consulta = consulta;
    }
    public Set getAdmRols() {
        return this.admRols;
    }
    
    public void setAdmRols(Set admRols) {
        this.admRols = admRols;
    }




}


