package entidades;
// Generated 02-sep-2016 14:54:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmSistema generated by hbm2java
 */
public class AdmSistema  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private String icono;
     private boolean activo;
     private Set admVistas = new HashSet(0);

    public AdmSistema() {
    }

	
    public AdmSistema(String nombre, boolean activo) {
        this.nombre = nombre;
        this.activo = activo;
    }
    public AdmSistema(String nombre, String descripcion, String icono, boolean activo, Set admVistas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.icono = icono;
       this.activo = activo;
       this.admVistas = admVistas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getAdmVistas() {
        return this.admVistas;
    }
    
    public void setAdmVistas(Set admVistas) {
        this.admVistas = admVistas;
    }




}


