package entidades;
// Generated 02-sep-2016 14:54:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmUsuario generated by hbm2java
 */
public class AdmUsuario  implements java.io.Serializable {


     private Integer id;
     private String usuarioInstitucional;
     private String avatar;
     private boolean activo;
     private Set admRols = new HashSet(0);
     private Set admAuditorias = new HashSet(0);

    public AdmUsuario() {
    }

	
    public AdmUsuario(String usuarioInstitucional, boolean activo) {
        this.usuarioInstitucional = usuarioInstitucional;
        this.activo = activo;
    }
    public AdmUsuario(String usuarioInstitucional, String avatar, boolean activo, Set admRols, Set admAuditorias) {
       this.usuarioInstitucional = usuarioInstitucional;
       this.avatar = avatar;
       this.activo = activo;
       this.admRols = admRols;
       this.admAuditorias = admAuditorias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsuarioInstitucional() {
        return this.usuarioInstitucional;
    }
    
    public void setUsuarioInstitucional(String usuarioInstitucional) {
        this.usuarioInstitucional = usuarioInstitucional;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getAdmRols() {
        return this.admRols;
    }
    
    public void setAdmRols(Set admRols) {
        this.admRols = admRols;
    }
    public Set getAdmAuditorias() {
        return this.admAuditorias;
    }
    
    public void setAdmAuditorias(Set admAuditorias) {
        this.admAuditorias = admAuditorias;
    }




}


