package entidades;
// Generated 02-sep-2016 14:54:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdmVista generated by hbm2java
 */
public class AdmVista  implements java.io.Serializable {


     private Integer id;
     private AdmSistema admSistema;
     private String url;
     private String descripcion;
     private Set admPermisos = new HashSet(0);

    public AdmVista() {
    }

	
    public AdmVista(String url) {
        this.url = url;
    }
    public AdmVista(AdmSistema admSistema, String url, String descripcion, Set admPermisos) {
       this.admSistema = admSistema;
       this.url = url;
       this.descripcion = descripcion;
       this.admPermisos = admPermisos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AdmSistema getAdmSistema() {
        return this.admSistema;
    }
    
    public void setAdmSistema(AdmSistema admSistema) {
        this.admSistema = admSistema;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAdmPermisos() {
        return this.admPermisos;
    }
    
    public void setAdmPermisos(Set admPermisos) {
        this.admPermisos = admPermisos;
    }




}


